/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

/**
 *
 * @author Jose Gpe Perez
 */
public class FormDashboard extends javax.swing.JFrame {
 int x, y;
    /**
     * Creates new form FormDashboard
     */
    public FormDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        rSProgressBar9 = new rojerusan.componentes.RSProgressBar();
        jSeparator7 = new javax.swing.JSeparator();
        rSProgressBar6 = new rojerusan.componentes.RSProgressBar();
        rSProgressBar7 = new rojerusan.componentes.RSProgressBar();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        rSProgressBar8 = new rojerusan.componentes.RSProgressBar();
        jSeparator11 = new javax.swing.JSeparator();
        rSProgressBar10 = new rojerusan.componentes.RSProgressBar();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        rSProgressBar5 = new rojerusan.componentes.RSProgressBar();
        rSProgressBar3 = new rojerusan.componentes.RSProgressBar();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        rSProgressBar1 = new rojerusan.componentes.RSProgressBar();
        jSeparator5 = new javax.swing.JSeparator();
        rSProgressBar4 = new rojerusan.componentes.RSProgressBar();
        rSProgressBar2 = new rojerusan.componentes.RSProgressBar();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        rSProgressCircle1 = new rojerusan.componentes.RSProgressCircle();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        rSProgressCircle2 = new rojerusan.componentes.RSProgressCircle();
        jLabel44 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        rSProgressCircle3 = new rojerusan.componentes.RSProgressCircle();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(49, 58, 73));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(49, 58, 73));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_User_32px.png"))); // NOI18N
        jLabel4.setText("Personal");
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 190, 40));

        jLabel5.setBackground(new java.awt.Color(39, 45, 57));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Dashboard_32px_2.png"))); // NOI18N
        jLabel5.setText("Dashboard");
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 190, 40));

        jLabel6.setBackground(new java.awt.Color(49, 58, 73));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_User_32px.png"))); // NOI18N
        jLabel6.setText("Alumnos");
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 190, 40));

        jLabel7.setBackground(new java.awt.Color(49, 58, 73));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Settings_28px.png"))); // NOI18N
        jLabel7.setText("Configuración");
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 220, 40));

        jLabel8.setBackground(new java.awt.Color(49, 58, 73));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Open_Book_32px.png"))); // NOI18N
        jLabel8.setText("Cursos");
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 40));

        jLabel9.setBackground(new java.awt.Color(49, 58, 73));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Exit_32px_2.png"))); // NOI18N
        jLabel9.setText("Salir");
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 190, 40));

        jLabel66.setBackground(new java.awt.Color(49, 58, 73));
        jLabel66.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Edit_32px_1.png"))); // NOI18N
        jLabel66.setText("Inscripciones");
        jLabel66.setOpaque(true);
        jPanel2.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 190, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 570));

        jPanel3.setBackground(new java.awt.Color(23, 100, 191));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(32, 132, 252));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Plus_Math_17px_1.png"))); // NOI18N
        jLabel1.setText("  Nuevo");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setOpaque(true);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 80, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Male_User_25px.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 40, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_Class_28px.png"))); // NOI18N
        jLabel3.setText("IDETS School");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Admin IDETS");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 40));

        jPanel4.setBackground(new java.awt.Color(233, 237, 240));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Version 1.0.0");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 30));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 880, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("DASHBOARD");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("MAY / 2018");
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 70, 20));

        jLabel41.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 102, 102));
        jLabel41.setText("23");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 20));

        jLabel42.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(102, 102, 102));
        jLabel42.setText("VENTAS DEL DIA");
        jPanel8.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        jLabel43.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 102, 102));
        jLabel43.setText("INGRESOS");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 20));

        jLabel45.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(102, 102, 102));
        jLabel45.setText("PRODUCTOS");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 20));

        jLabel46.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(23, 100, 191));
        jLabel46.setText("$ 11,123.00");
        jPanel8.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 20));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 210, 170));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(23, 100, 191));
        jLabel28.setText("32");
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 20));

        jLabel29.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("30");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 20, 20));

        jLabel30.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("40");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 20, 20));

        jLabel31.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("10");
        jLabel31.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel11.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 20, 20));

        jLabel32.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("20");
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel11.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 20, 20));

        jLabel33.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("0");
        jLabel33.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel11.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 20, 20));

        rSProgressBar9.setBorder(null);
        rSProgressBar9.setForeground(new java.awt.Color(229, 46, 112));
        rSProgressBar9.setMaximum(40);
        rSProgressBar9.setOrientation(1);
        rSProgressBar9.setString("");
        jPanel11.add(rSProgressBar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 10, 80));
        jPanel11.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, 10));

        rSProgressBar6.setBorder(null);
        rSProgressBar6.setForeground(new java.awt.Color(229, 46, 112));
        rSProgressBar6.setMaximum(40);
        rSProgressBar6.setOrientation(1);
        rSProgressBar6.setValue(32);
        rSProgressBar6.setString("");
        jPanel11.add(rSProgressBar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 10, 80));

        rSProgressBar7.setBorder(null);
        rSProgressBar7.setForeground(new java.awt.Color(23, 100, 191));
        rSProgressBar7.setMaximum(40);
        rSProgressBar7.setOrientation(1);
        rSProgressBar7.setValue(32);
        rSProgressBar7.setString("");
        jPanel11.add(rSProgressBar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 10, 80));
        jPanel11.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, -1));
        jPanel11.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 160, 10));
        jPanel11.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 10));

        rSProgressBar8.setBorder(null);
        rSProgressBar8.setForeground(new java.awt.Color(229, 46, 112));
        rSProgressBar8.setMaximum(40);
        rSProgressBar8.setOrientation(1);
        rSProgressBar8.setValue(15);
        rSProgressBar8.setString("");
        jPanel11.add(rSProgressBar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 10, 80));
        jPanel11.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, 10));

        rSProgressBar10.setBorder(null);
        rSProgressBar10.setForeground(new java.awt.Color(229, 46, 112));
        rSProgressBar10.setMaximum(40);
        rSProgressBar10.setOrientation(1);
        rSProgressBar10.setValue(5);
        rSProgressBar10.setString("");
        jPanel11.add(rSProgressBar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 10, 80));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("JUE");
        jPanel11.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 30, 20));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("DOM");
        jPanel11.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 30, 20));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("LUN");
        jPanel11.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 30, 20));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("MAR");
        jPanel11.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 30, 20));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("MIE");
        jPanel11.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 30, 20));

        jLabel39.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("NUEVAS INSCRIPCIONES");
        jPanel11.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 20));

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 210, 170));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(23, 100, 191));
        jLabel13.setText("$ 35,234.78");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("30");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 20, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("40");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 20, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("10");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 20, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("20");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 20, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("0");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 20, 20));
        jPanel6.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, 10));

        rSProgressBar5.setBorder(null);
        rSProgressBar5.setForeground(new java.awt.Color(229, 46, 112));
        rSProgressBar5.setMaximum(40);
        rSProgressBar5.setOrientation(1);
        rSProgressBar5.setValue(30);
        rSProgressBar5.setString("");
        jPanel6.add(rSProgressBar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 10, 80));

        rSProgressBar3.setBorder(null);
        rSProgressBar3.setForeground(new java.awt.Color(23, 100, 191));
        rSProgressBar3.setMaximum(40);
        rSProgressBar3.setOrientation(1);
        rSProgressBar3.setValue(35);
        rSProgressBar3.setString("");
        jPanel6.add(rSProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 10, 80));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, -1));
        jPanel6.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 160, 10));

        rSProgressBar1.setBorder(null);
        rSProgressBar1.setForeground(new java.awt.Color(229, 46, 112));
        rSProgressBar1.setMaximum(40);
        rSProgressBar1.setOrientation(1);
        rSProgressBar1.setValue(25);
        rSProgressBar1.setString("");
        jPanel6.add(rSProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 10, 80));
        jPanel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 10));

        rSProgressBar4.setBorder(null);
        rSProgressBar4.setForeground(new java.awt.Color(229, 46, 112));
        rSProgressBar4.setMaximum(40);
        rSProgressBar4.setOrientation(1);
        rSProgressBar4.setValue(15);
        rSProgressBar4.setString("");
        jPanel6.add(rSProgressBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 10, 80));

        rSProgressBar2.setBorder(null);
        rSProgressBar2.setForeground(new java.awt.Color(229, 46, 112));
        rSProgressBar2.setMaximum(40);
        rSProgressBar2.setOrientation(1);
        rSProgressBar2.setValue(15);
        rSProgressBar2.setString("");
        jPanel6.add(rSProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 10, 80));
        jPanel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, 10));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("DIC");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 30, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("AGO");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 30, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("SEP");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 30, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("OCT");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 30, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("NOV");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 30, 20));

        jLabel24.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("INGRESOS DEL MES");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, 170));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSProgressCircle1.setForeground(new java.awt.Color(23, 100, 191));
        rSProgressCircle1.setMaximum(350);
        rSProgressCircle1.setToolTipText("");
        rSProgressCircle1.setValue(296);
        rSProgressCircle1.setFont(new java.awt.Font("Roboto Bold", 1, 10)); // NOI18N
        rSProgressCircle1.setString("83%");
        jPanel7.add(rSProgressCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 100));

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("MENSUALIDAD");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText(" PAGADAS");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 10));

        jPanel5.setBackground(new java.awt.Color(23, 100, 191));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 10, 10));

        jLabel27.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText(" VENCIDAS");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, 10));

        jPanel10.setBackground(new java.awt.Color(229, 46, 112));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel10.setOpaque(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 10, 10));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, 170));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSProgressCircle2.setForeground(new java.awt.Color(163, 61, 140));
        rSProgressCircle2.setMaximum(350);
        rSProgressCircle2.setToolTipText("");
        rSProgressCircle2.setValue(296);
        rSProgressCircle2.setFont(new java.awt.Font("Roboto Bold", 1, 10)); // NOI18N
        rSProgressCircle2.setString("76%");
        jPanel9.add(rSProgressCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 100));

        jLabel44.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(102, 102, 102));
        jLabel44.setText("MENSUALIDAD");
        jPanel9.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        jLabel47.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 102, 102));
        jLabel47.setText(" PAGADAS");
        jPanel9.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 70, 10));

        jPanel12.setBackground(new java.awt.Color(163, 61, 140));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 10, 10));

        jLabel48.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(102, 102, 102));
        jLabel48.setText(" VENCIDAS");
        jPanel9.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 70, 10));

        jPanel13.setBackground(new java.awt.Color(229, 46, 112));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel13.setOpaque(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 10, 10));

        jLabel64.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(23, 100, 191));
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("258");
        jPanel9.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 70, 20));

        jLabel65.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(102, 102, 102));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("92");
        jPanel9.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 20));

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 210, 170));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(102, 102, 102));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_User_Groups_40px.png"))); // NOI18N
        jPanel14.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 70, 40));

        jLabel50.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(102, 102, 102));
        jLabel50.setText("296");
        jPanel14.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 20));

        jLabel51.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(102, 102, 102));
        jLabel51.setText("ALUMNOS");
        jPanel14.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jLabel52.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(102, 102, 102));
        jLabel52.setText("HOY");
        jPanel14.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 20));

        jLabel53.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(102, 102, 102));
        jLabel53.setText("AYER");
        jPanel14.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 20));

        jLabel54.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(229, 46, 112));
        jLabel54.setText("295");
        jPanel14.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 20));

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 210, 170));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(102, 102, 102));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_User_Groups_40px.png"))); // NOI18N
        jPanel15.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 70, 40));

        jLabel56.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(102, 102, 102));
        jLabel56.setText("1,232");
        jPanel15.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 20));

        jLabel57.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(102, 102, 102));
        jLabel57.setText("USUARIOS");
        jPanel15.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jLabel58.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(102, 102, 102));
        jLabel58.setText("HOY");
        jPanel15.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 20));

        jLabel59.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(102, 102, 102));
        jLabel59.setText("AYER");
        jPanel15.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 20));

        jLabel60.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(23, 100, 191));
        jLabel60.setText("1,237");
        jPanel15.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 20));

        jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 210, 170));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSProgressCircle3.setForeground(new java.awt.Color(229, 46, 112));
        rSProgressCircle3.setMaximum(350);
        rSProgressCircle3.setToolTipText("");
        rSProgressCircle3.setValue(296);
        rSProgressCircle3.setFont(new java.awt.Font("Roboto Bold", 1, 10)); // NOI18N
        rSProgressCircle3.setString("296");
        jPanel16.add(rSProgressCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 100));

        jLabel61.setFont(new java.awt.Font("Segoe UI Semilight", 1, 11)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(102, 102, 102));
        jLabel61.setText("TOTAL DE ALUMNOS");
        jPanel16.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        jLabel62.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(102, 102, 102));
        jLabel62.setText(" OCUPADOS");
        jPanel16.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 10));

        jPanel17.setBackground(new java.awt.Color(229, 46, 112));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 10, 10));

        jLabel63.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(102, 102, 102));
        jLabel63.setText(" DISPONIBLES");
        jPanel16.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, 10));

        jPanel18.setBackground(new java.awt.Color(229, 46, 112));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel18.setOpaque(false);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 10, 10));

        jPanel4.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 210, 170));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 910, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
 x = evt.getX();
        y = evt.getY();           // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
 this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);           // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private rojerusan.componentes.RSProgressBar rSProgressBar1;
    private rojerusan.componentes.RSProgressBar rSProgressBar10;
    private rojerusan.componentes.RSProgressBar rSProgressBar2;
    private rojerusan.componentes.RSProgressBar rSProgressBar3;
    private rojerusan.componentes.RSProgressBar rSProgressBar4;
    private rojerusan.componentes.RSProgressBar rSProgressBar5;
    private rojerusan.componentes.RSProgressBar rSProgressBar6;
    private rojerusan.componentes.RSProgressBar rSProgressBar7;
    private rojerusan.componentes.RSProgressBar rSProgressBar8;
    private rojerusan.componentes.RSProgressBar rSProgressBar9;
    private rojerusan.componentes.RSProgressCircle rSProgressCircle1;
    private rojerusan.componentes.RSProgressCircle rSProgressCircle2;
    private rojerusan.componentes.RSProgressCircle rSProgressCircle3;
    // End of variables declaration//GEN-END:variables
}
